spring:
  profiles:
    active: development
---
server:
  port: 9090
spring:
  application:
    name: inventory-service
  profiles: development
  neo4j:
    host: ${SPRING_NEO4J_HOST:222.201.187.167}
    port: ${SPRING_NEO4J_PORT:7474}
    username: neo4j
    password: wujiechu
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的insert脚本
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR